[package]
name = "get_xml_from_pdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = "0.7.2"
clap = {version = "4.0.23", features = ["derive"]}
